// axum = web framework for APIs in Rust
use axum::{
    extract::Path,                    // allows pulling path parameters from request URL (e.g. /users/:id)
    http::StatusCode,                 // http status codes
    response::Json,                   // wraps data so axum automatically serializes to json in http response
    routing::{get, post},             // helpers for defining GET/POST routes
    Router,                           // core object for defining middleware
};
use serde::{Deserialize, Serialize};  // traits so structs can be converted to/from json
use std::collections::HashMap;

#[derive(Serialize, Deserialize)]     // tells serde to automatically use json serialization/deserialization for struct
struct User {                     
    id: u32,
    name: String,
    email: String,
}

#[derive(Deserialize)]               // only deserialize (only reads from json requests, not sent back)
struct CreateUser {
    name: String,
    email: String,
}

/* handlers are async functions called when request matches route */

// handler for GET /
async fn root() -> &'static str {
    "Hello, World!"
}

// handler for GET /users
async fn get_users() -> Json<Vec<User>> {
    // normally would query database
    let users = vec![
        User {
            id: 1,
            name: "Konstantinos".to_string(),
            email: "rokanasc94@hotmail.com".to_string(),
        },
        User {
            id: 2,
            name: "Rokanas".to_string(),
            email: "fakeemail@hotmail.com".to_string(),
        },
    ];
    Json(users)
}

// handler for GET /users/:id
async fn get_user(Path(id): Path<u32>) -> Result<Json<User>, StatusCode> {
    // normally would query database
    if id == 1 {
        Ok(Json(User {
            id: 1,
            name: "Konstantinos".to_string(),
            email: "rokanasc94@hotmail.com".to_string(),
        }))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}

// handler for POST /users
async fn create_user(Json(payload): Json<CreateUser>) -> Result<Json<User>, StatusCode> {
    // normally would save to database
    let user = User {
        id: 3, // this would be generated by database
        name: payload.name,
        email: payload.email,
    };
    Ok(Json(user))
}

// hndler for GET /health
async fn health_check() -> Json<HashMap<String, String>> {
    let mut status = HashMap::new();
    status.insert("status".to_string(), "healthy".to_string());
    status.insert("version".to_string(), "1.0.0".to_string());
    Json(status)
}

#[tokio::main]  // macro that runs main function inside tokio's async runtime (needed for async i/o in axum)
async fn main() {
    // register routes
    let app = Router::new() 
        .route("/", get(root))
        .route("/health", get(health_check))
        .route("/users", get(get_users))
        .route("/users", post(create_user))
        .route("/users/:id", get(get_user));

    // run server (bind tcp listener to all interfaces on port 3000)
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("Server running on http://localhost:3000");
    axum::serve(listener, app).await.unwrap();
}